services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    env_file:
      - secrets.env
    volumes:
      - data:/var/lib/rabbitmq
volumes:
  data: