"""Add data and is_send columns

Revision ID: 6c7f1b396d5b
Revises: 
Create Date: 2024-12-12 00:35:20.164847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7f1b396d5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('hashtag', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('data', sa.JSON(), nullable=True))
    op.add_column('accounts', sa.Column('is_send', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_send')
    op.drop_column('accounts', 'data')
    op.drop_column('accounts', 'hashtag')
    # ### end Alembic commands ###
