"""delete is_send and is_processed

Revision ID: 2ab315967e94
Revises: 8481558fb9f9
Create Date: 2025-01-08 14:13:18.724571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab315967e94'
down_revision: Union[str, None] = '8481558fb9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_processed')
    op.drop_column('accounts', 'is_send')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_send', sa.BOOLEAN(), nullable=True))
    op.add_column('accounts', sa.Column('is_processed', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
