"""rename status_num -> status

Revision ID: 7b9713aec458
Revises: a0c798f65b56
Create Date: 2025-02-24 09:54:07.648307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b9713aec458'
down_revision: Union[str, None] = 'a0c798f65b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Определяем новый тип ENUM
new_enum = postgresql.ENUM(
    'UNKNOWN', 'ARTIST', 'BEATMAKER', 'LABEL', 'MARKET', 'COMMUNITY', 'OTHER',
    name='account_type_enum'
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем новый тип ENUM
    new_enum.create(op.get_bind(), checkfirst=True)

    # Приводим существующие данные к новому типу и изменяем тип колонки
    op.execute('''
        ALTER TABLE accounts
        ALTER COLUMN account_type TYPE account_type_enum
        USING account_type::account_type_enum
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем тип колонки к VARCHAR
    op.execute('''
        ALTER TABLE accounts
        ALTER COLUMN account_type TYPE VARCHAR(9)
        USING account_type::VARCHAR(9)
    ''')

    # Удаляем тип ENUM
    new_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
