"""delete string status

Revision ID: 90c175c30d08
Revises: baf45ba718a1
Create Date: 2025-02-24 09:45:31.130923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c175c30d08'
down_revision: Union[str, None] = 'baf45ba718a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('status', sa.VARCHAR(length=10), server_default=sa.text("'PARSING'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
