"""rename status_num -> status

Revision ID: a0c798f65b56
Revises: 90c175c30d08
Create Date: 2025-02-24 09:46:28.349526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c798f65b56'
down_revision: Union[str, None] = '90c175c30d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('status', sa.Integer(), server_default=sa.text('5'), nullable=False))
    op.drop_column('accounts', 'status_num')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('status_num', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'status')
    # ### end Alembic commands ###
