"""added status for account_posts

Revision ID: adc0d866105f
Revises: 7b9713aec458
Create Date: 2025-03-17 21:21:04.810269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc0d866105f'
down_revision: Union[str, None] = '7b9713aec458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_posts', sa.Column('status', sa.Integer(), server_default=sa.text('5'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_posts', 'status')
    # ### end Alembic commands ###
