"""status string -> num

Revision ID: baf45ba718a1
Revises: 23a3215a9deb
Create Date: 2025-02-24 09:44:37.608378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf45ba718a1'
down_revision: Union[str, None] = '23a3215a9deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('status_num', sa.Integer(), server_default=sa.text('5'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'status_num')
    # ### end Alembic commands ###
